[package]
name = "readrust"
version = "0.1.0"
authors = ["Shreyas Lad <shadowtemplates@gmail.com>"]

[dependencies]
clap = "2.29"
reqwest = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
prettytable-rs = "0.6"